spring.application.name=ConnectToDatabase
spring.datasource.username=root
spring.datasource.password=srujan
spring.datasource.url=jdbc:mysql://localhost:3306/fullstackdevelopment
spring.jpa.hibernate.ddl-auto=update
